import type { Product, Brand, Category, Order, User, Coupon, AdminDashboardMetrics } from '@/types'

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Roupas', slug: 'roupas', description: 'Camisetas, calças, jaquetas e agasalhos de alta qualidade', productCount: 42 },
  { id: 'cat-2', name: 'Calçados', slug: 'calcados', description: 'Tênis urbanos, sapatos de couro e calçados esportivos', productCount: 28 },
  { id: 'cat-3', name: 'Acessórios', slug: 'acessorios', description: 'Bones, mochilas, relógios e óculos de sol', productCount: 19 },
]

export const MOCK_BRANDS: Brand[] = [
  { id: 'b-1', name: 'Aura Studio', productCount: 15 },
  { id: 'b-2', name: 'Nordic Peak', productCount: 22 },
  { id: 'b-3', name: 'Urban Craft', productCount: 18 },
  { id: 'b-4', name: 'Vanguard Threads', productCount: 34 },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Jaqueta Puffer Oversized Tech',
    slug: 'jaqueta-puffer-oversized-tech',
    description: 'Jaqueta puffer unissex confeccionada em tecido de poliamida impermeável com isolamento térmico de alto desempenho. Conta com múltiplos bolsos utilitários internos e ajuste elástico na barra.',
    price: 489.90,
    originalPrice: 599.90,
    category: 'jaquetas',
    brand: 'Urban Craft',
    gender: 'unissex',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800',
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 38,
    isNew: true,
    tags: ['Inverno', 'Urban', 'Impermeável'],
    variants: [
      { id: 'v1', sku: 'JP-BLK-P', size: 'P', color: 'Preto', colorHex: '#000000', stockQuantity: 8 },
      { id: 'v2', sku: 'JP-BLK-M', size: 'M', color: 'Preto', colorHex: '#000000', stockQuantity: 12 },
      { id: 'v3', sku: 'JP-BLK-G', size: 'G', color: 'Preto', colorHex: '#000000', stockQuantity: 4 },
      { id: 'v4', sku: 'JP-SLV-M', size: 'M', color: 'Prata Metalizado', colorHex: '#94a3b8', stockQuantity: 6 },
    ],
  },
  {
    id: 'prod-2',
    name: 'Camiseta Minimal Cotton Heavyweight',
    slug: 'camiseta-minimal-cotton-heavyweight',
    description: 'Camiseta confeccionada em 100% algodão egípcio de gramatura pesada (240g/m²). Gola reforçada com ribana de 3cm e caimento estruturado moderno.',
    price: 139.90,
    category: 'camisas',
    brand: 'Aura Studio',
    gender: 'masculino',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&q=80&w=800',
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 94,
    tags: ['Básico Premium', 'Heavyweight'],
    variants: [
      { id: 'v5', sku: 'CM-WHT-P', size: 'P', color: 'Branco Off-White', colorHex: '#f8fafc', stockQuantity: 15 },
      { id: 'v6', sku: 'CM-WHT-M', size: 'M', color: 'Branco Off-White', colorHex: '#f8fafc', stockQuantity: 20 },
      { id: 'v7', sku: 'CM-WHT-G', size: 'G', color: 'Branco Off-White', colorHex: '#f8fafc', stockQuantity: 10 },
      { id: 'v8', sku: 'CM-SAN-M', size: 'M', color: 'Areia', colorHex: '#d97706', stockQuantity: 7 },
    ],
  },
  {
    id: 'prod-3',
    name: 'Tênis Runner Phantom Neo',
    slug: 'tenis-runner-phantom-neo',
    description: 'Tênis esportivo com tecnologia de amortecimento em gel no calcanhar, cabedal em knit respirável de peça única e solado em borracha antiderrapante de alta tração.',
    price: 629.00,
    originalPrice: 749.00,
    category: 'tenis',
    brand: 'Nordic Peak',
    gender: 'unissex',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800',
    ],
    featured: true,
    rating: 4.95,
    reviewCount: 142,
    isNew: true,
    tags: ['Running', 'Gel Cushion'],
    variants: [
      { id: 'v9', sku: 'TR-RED-39', size: '39', color: 'Vermelho Vermilion', colorHex: '#ef4444', stockQuantity: 5 },
      { id: 'v10', sku: 'TR-RED-40', size: '40', color: 'Vermelho Vermilion', colorHex: '#ef4444', stockQuantity: 9 },
      { id: 'v11', sku: 'TR-RED-41', size: '41', color: 'Vermelho Vermilion', colorHex: '#ef4444', stockQuantity: 11 },
      { id: 'v12', sku: 'TR-RED-42', size: '42', color: 'Vermelho Vermilion', colorHex: '#ef4444', stockQuantity: 3 },
    ],
  },
  {
    id: 'prod-4',
    name: 'Calça Cargo Utility Ripstop',
    slug: 'calca-cargo-utility-ripstop',
    description: 'Calça cargo confeccionada em tecido Ripstop anti-rasgo. Possui 6 bolsos funcionais, cintura ajustável por cordão e barra com regulagem via stopper.',
    price: 299.90,
    category: 'calcas',
    brand: 'Vanguard Threads',
    gender: 'masculino',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=800',
    ],
    featured: false,
    rating: 4.7,
    reviewCount: 56,
    tags: ['Streetwear', 'Tactical'],
    variants: [
      { id: 'v13', sku: 'CC-OLV-38', size: '38', color: 'Verde Oliva', colorHex: '#3f6212', stockQuantity: 6 },
      { id: 'v14', sku: 'CC-OLV-40', size: '40', color: 'Verde Oliva', colorHex: '#3f6212', stockQuantity: 14 },
      { id: 'v15', sku: 'CC-OLV-42', size: '42', color: 'Verde Oliva', colorHex: '#3f6212', stockQuantity: 8 },
    ],
  },
  {
    id: 'prod-5',
    name: 'Mochila Commuter Waterproof 25L',
    slug: 'mochila-commuter-waterproof-25l',
    description: 'Mochila urbana impermeável com compartimento acolchoado para notebook até 16 polegadas, fecho magnético fidlock e entrada USB externa para carregamento.',
    price: 349.90,
    originalPrice: 399.90,
    category: 'acessorios',
    brand: 'Nordic Peak',
    gender: 'unissex',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    ],
    featured: true,
    rating: 4.85,
    reviewCount: 71,
    tags: ['Impermeável', 'Tech'],
    variants: [
      { id: 'v16', sku: 'MC-BLK-UNI', size: 'Único', color: 'Preto Matte', colorHex: '#1e293b', stockQuantity: 18 },
    ],
  },
  {
    id: 'prod-6',
    name: 'Óculos de Sol Aviador Titanio Minimalist',
    slug: 'oculos-de-sol-aviador-titanio',
    description: 'Armação ultra-leve em liga de titânio acetinado com lentes polarizadas de policarbonato e proteção total UV400 contra raios solares.',
    price: 219.00,
    category: 'acessorios',
    brand: 'Aura Studio',
    gender: 'unissex',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800',
    ],
    featured: false,
    rating: 4.6,
    reviewCount: 29,
    tags: ['UV400', 'Titânio'],
    variants: [
      { id: 'v17', sku: 'OC-GLD-UNI', size: 'Único', color: 'Dourado Fosco', colorHex: '#eab308', stockQuantity: 12 },
    ],
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'PED-2026-8891',
    createdAt: '2026-07-28T14:32:00Z',
    status: 'DELIVERED',
    totalAmount: 629.80,
    subtotalAmount: 629.80,
    discountAmount: 0,
    shippingFee: 0,
    paymentMethod: 'PIX',
    shippingAddress: {
      street: 'Av. Paulista',
      number: '1000',
      complement: 'Apto 124',
      neighborhood: 'Bela Vista',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01310-100',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Jaqueta Puffer Oversized Tech',
        productImage: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800',
        size: 'M',
        color: 'Preto',
        unitPrice: 489.90,
        quantity: 1,
        subtotal: 489.90,
      },
      {
        id: 'item-2',
        productId: 'prod-2',
        productName: 'Camiseta Minimal Cotton Heavyweight',
        productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800',
        size: 'M',
        color: 'Branco Off-White',
        unitPrice: 139.90,
        quantity: 1,
        subtotal: 139.90,
      },
    ],
  },
  {
    id: 'ord-1002',
    orderNumber: 'PED-2026-9014',
    createdAt: '2026-07-30T09:15:00Z',
    status: 'SHIPPED',
    totalAmount: 629.00,
    subtotalAmount: 629.00,
    discountAmount: 0,
    shippingFee: 0,
    paymentMethod: 'CREDIT_CARD',
    shippingAddress: {
      street: 'Rua Oscar Freire',
      number: '450',
      neighborhood: 'Jardins',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01426-000',
    },
    items: [
      {
        id: 'item-3',
        productId: 'prod-3',
        productName: 'Tênis Runner Phantom Neo',
        productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
        size: '41',
        color: 'Vermelho Vermilion',
        unitPrice: 629.00,
        quantity: 1,
        subtotal: 629.00,
      },
    ],
  },
]

export const MOCK_COUPONS: Coupon[] = [
  { id: 'c-1', code: 'BEMVINDO10', discountPercentage: 10, minPurchaseAmount: 150, expiresAt: '2026-12-31', active: true, usageCount: 142 },
  { id: 'c-2', code: 'WINTER20', discountPercentage: 20, minPurchaseAmount: 400, expiresAt: '2026-08-31', active: true, usageCount: 89 },
]

export const MOCK_USERS: User[] = [
  { id: 'u-1', name: 'Alexandre Silva', email: 'alexandre@example.com', role: 'CUSTOMER', createdAt: '2026-01-15' },
  { id: 'u-2', name: 'Juliana Mendes', email: 'juliana@example.com', role: 'ADMIN', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200', createdAt: '2025-11-20' },
]

export const MOCK_METRICS: AdminDashboardMetrics = {
  totalRevenue: 148920.50,
  totalOrders: 312,
  totalCustomers: 854,
  totalProducts: 42,
  recentOrders: MOCK_ORDERS,
  lowStockProducts: [MOCK_PRODUCTS[0], MOCK_PRODUCTS[2]],
}
