/**
 * Códigos de erro da aplicação.
 * Usados para identificar erros programaticamente no frontend.
 */
export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'AUTH001',
  ACCOUNT_LOCKED: 'AUTH002',
  SESSION_EXPIRED: 'AUTH003',
  SESSION_REVOKED: 'AUTH004',
  TOKEN_REUSE_DETECTED: 'AUTH005',
  INVALID_TOKEN: 'AUTH006',
  INVALID_RESET_TOKEN: 'AUTH007',
  RESET_TOKEN_EXPIRED: 'AUTH008',
  EMAIL_ALREADY_EXISTS: 'AUTH009',
  ACCOUNT_INACTIVE: 'AUTH010',
  CSRF_TOKEN_INVALID: 'AUTH011',
  ACCOUNT_NOT_FOUND: 'AUTH012',

  // Authorization
  UNAUTHORIZED: 'AUTHZ001',
  FORBIDDEN: 'AUTHZ002',
  INSUFFICIENT_PERMISSIONS: 'AUTHZ003',

  // Validation
  VALIDATION_ERROR: 'VALID001',
  INVALID_UUID: 'VALID002',
  INVALID_FILE_TYPE: 'VALID003',
  FILE_TOO_LARGE: 'VALID004',
  INVALID_IMAGE: 'VALID005',

  // Users
  USER_NOT_FOUND: 'USER001',
  USER_ALREADY_EXISTS: 'USER002',

  // Products
  PRODUCT_NOT_FOUND: 'PROD001',
  VARIANT_NOT_FOUND: 'PROD002',
  INSUFFICIENT_STOCK: 'PROD003',
  PRODUCT_INACTIVE: 'PROD004',

  // Categories
  CATEGORY_NOT_FOUND: 'CAT001',
  CATEGORY_SLUG_EXISTS: 'CAT002',

  // Brands
  BRAND_NOT_FOUND: 'BRAND001',
  BRAND_SLUG_EXISTS: 'BRAND002',

  // Cart
  CART_NOT_FOUND: 'CART001',
  CART_ITEM_NOT_FOUND: 'CART002',
  CART_EMPTY: 'CART003',

  // Orders
  ORDER_NOT_FOUND: 'ORDER001',
  ORDER_CANNOT_CANCEL: 'ORDER002',
  ORDER_ALREADY_CANCELLED: 'ORDER003',

  // Addresses
  ADDRESS_NOT_FOUND: 'ADDR001',
  ADDRESS_LIMIT_EXCEEDED: 'ADDR002',

  // Reviews
  REVIEW_NOT_FOUND: 'REV001',
  REVIEW_ALREADY_EXISTS: 'REV002',
  REVIEW_NOT_ELIGIBLE: 'REV003',

  // System
  INTERNAL_SERVER_ERROR: 'SYS001',
  SERVICE_UNAVAILABLE: 'SYS002',
  RATE_LIMIT_EXCEEDED: 'SYS003',
  NOT_FOUND: 'SYS004',
  METHOD_NOT_ALLOWED: 'SYS005',
  PAYLOAD_TOO_LARGE: 'SYS006',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
